/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.kohisop;

/**
 *
 * @author Lenovo
 */
public class FoodCard extends javax.swing.JPanel {

    /**
     * Creates new form FoodCard
     */
    public FoodCard() {
        initComponents();
        // Override layout supaya card rapi
        setLayout(new java.awt.BorderLayout());
        setPreferredSize(new java.awt.Dimension(250, 280));
        setMinimumSize(new java.awt.Dimension(250, 280));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220), 1));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelGambar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        labelGambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(labelGambar)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(labelGambar)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    // ... (kode layout bawaan NetBeans yang panjang di atasnya) ...
    // </editor-fold>                        
    public void setMenuData(entity.Menu item) {
        removeAll();

        // === PANEL GAMBAR ===
        javax.swing.JLabel imgLabel = new javax.swing.JLabel();
        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setPreferredSize(new java.awt.Dimension(250, 180));
        imgLabel.setOpaque(true);
        imgLabel.setBackground(new java.awt.Color(240, 240, 240));

        try {
            java.net.URL imgURL = getClass().getResource(item.getImagePath());
            if (imgURL != null) {
                javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(imgURL);
                java.awt.Image imgSkala = iconAsli.getImage()
                    .getScaledInstance(250, 180, java.awt.Image.SCALE_SMOOTH);
                imgLabel.setIcon(new javax.swing.ImageIcon(imgSkala));
            } else {
                imgLabel.setText("No Image");
            }
        } catch (Exception e) {
            imgLabel.setText("Error");
        }

        // === PANEL TEKS ===
        javax.swing.JPanel infoPanel = new javax.swing.JPanel();
        infoPanel.setLayout(new javax.swing.BoxLayout(infoPanel, javax.swing.BoxLayout.Y_AXIS));
        infoPanel.setBackground(java.awt.Color.WHITE);
        infoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        javax.swing.JLabel namaLabel = new javax.swing.JLabel(item.getName());
        namaLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        namaLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

        javax.swing.JLabel hargaLabel = new javax.swing.JLabel(
            item.getCodeMenu() + " - " + String.format("Rp %,.0f", item.getPrice())
        );
        hargaLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));
        hargaLabel.setForeground(new java.awt.Color(120, 120, 120));
        hargaLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

        infoPanel.add(namaLabel);
        infoPanel.add(javax.swing.Box.createVerticalStrut(4));
        infoPanel.add(hargaLabel);

        add(imgLabel, java.awt.BorderLayout.CENTER);
        add(infoPanel, java.awt.BorderLayout.SOUTH);

        revalidate();
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelGambar;
    // End of variables declaration//GEN-END:variables
}